spring.application.name=skyplanner

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/skyplanner
spring.datasource.username=skyplanner
spring.datasource.password=skyplanner
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Health Endpoint
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

